name: vandalino-family
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: dsv101/vandalino-family
  name: vandalino-family
